# TASK 1 : PREPARING

In [3]:
import numpy as np
import pandas as pd

## 1.1 -- Importing dataset

In [33]:
df = pd.read_csv("./data/tools.csv")
df

,Name,Variation,Body Title,DIY,Customize,Kit Cost,Uses,Stack Size,Buy,Sell,...,Size,Set,Miles Price,Source,Source Notes,Version,Filename,Variant ID,Internal ID,Unique Entry ID
0,axe,NaN,NaN,Yes,No,NaN,100,1,2500,625,...,1x1,NaN,NaN,Nook's Cranny; Crafting,NaN,1.0.0,ToolAxe,NaN,2100,iR9zzEhzpbXTGdkR4
1,bamboo wand,NaN,NaN,Yes,No,NaN,Unlimited,1,NFS,3900,...,1x1,NaN,NaN,Crafting,NaN,1.0.0,ToolStickBamboo,NaN,7590,YLjDYt9NhwTgoXhLD
2,bug wand,NaN,NaN,No,No,NaN,Unlimited,1,NFS,1500,...,1x1,NaN,NaN,Bug-Off,NaN,1.0.0,ToolStcikInsect,NaN,8769,vqp4KBeWgZjYbFj7Z
3,Bunny Day wand,NaN,NaN,Yes,No,NaN,Unlimited,1,NFS,11100,...,1x1,NaN,NaN,Crafting,NaN,1.1.0a,ToolStickEgg,NaN,12578,26wk773sY75rKY2P4
4,cherry-blossom wand,NaN,NaN,Yes,No,NaN,Unlimited,1,NFS,2700,...,1x1,NaN,NaN,Crafting,NaN,1.0.0,ToolStickCherryblossom,NaN,7589,WHHbg5ZqTMu4J2wm5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,watering can,White,Color,Yes,Yes,1.0,60,1,2400,600,...,1x1,NaN,NaN,Crafting,NaN,1.0.0,ToolWatering_Remake_6_0,6_0,2379,Z7ggDgjzNii2RWjNQ
196,watering can,Black,Color,Yes,Yes,1.0,60,1,2400,600,...,1x1,NaN,NaN,Crafting,NaN,1.0.0,ToolWatering_Remake_7_0,7_0,2379,77zFHmNrGhuJAvvjA
197,wedding wand,NaN,NaN,Yes,No,NaN,Unlimited,1,NFS,3500,...,1x1,NaN,NaN,Wedding Season,NaN,1.2.0,ToolStickJune,NaN,12695,syPb2baTrP3zqi66f
198,windflower wand,NaN,NaN,Yes,No,NaN,Unlimited,1,NFS,1580,...,1x1,NaN,NaN,Crafting,NaN,1.0.0,ToolStickAnemones,NaN,5084,ERMKczYuvS6Eff7C9
199,worn axe,NaN,NaN,No,No,NaN,3,1,40,10,...,1x1,NaN,NaN,May Day Tour,Only available during May Day Tour,1.2.0,ToolAxeFragile,NaN,12615,xqXJch47cQrNT65jG

In [19]:
df.head(5)

,Name,Variation,Body Title,DIY,Customize,Kit Cost,Uses,Stack Size,Buy,Sell,...,Size,Set,Miles Price,Source,Source Notes,Version,Filename,Variant ID,Internal ID,Unique Entry ID
0,axe,NaN,NaN,Yes,No,NaN,100,1,2500,625,...,1x1,NaN,NaN,Nook's Cranny; Crafting,NaN,1.0.0,ToolAxe,NaN,2100,iR9zzEhzpbXTGdkR4
1,bamboo wand,NaN,NaN,Yes,No,NaN,Unlimited,1,NFS,3900,...,1x1,NaN,NaN,Crafting,NaN,1.0.0,ToolStickBamboo,NaN,7590,YLjDYt9NhwTgoXhLD
2,bug wand,NaN,NaN,No,No,NaN,Unlimited,1,NFS,1500,...,1x1,NaN,NaN,Bug-Off,NaN,1.0.0,ToolStcikInsect,NaN,8769,vqp4KBeWgZjYbFj7Z
3,Bunny Day wand,NaN,NaN,Yes,No,NaN,Unlimited,1,NFS,11100,...,1x1,NaN,NaN,Crafting,NaN,1.1.0a,ToolStickEgg,NaN,12578,26wk773sY75rKY2P4
4,cherry-blossom wand,NaN,NaN,Yes,No,NaN,Unlimited,1,NFS,2700,...,1x1,NaN,NaN,Crafting,NaN,1.0.0,ToolStickCherryblossom,NaN,7589,WHHbg5ZqTMu4J2wm5

## 1.2 -- Filtering input

In [20]:
df = df[['Name', 'Uses', 'Sell', 'Variation', 'Set', 'Customize', 'Source', 'Filename', 'Internal ID']]
df

,Name,Uses,Sell,Variation,Set,Customize,Source,Filename,Internal ID
0,axe,100,625,NaN,NaN,No,Nook's Cranny; Crafting,ToolAxe,2100
1,bamboo wand,Unlimited,3900,NaN,NaN,No,Crafting,ToolStickBamboo,7590
2,bug wand,Unlimited,1500,NaN,NaN,No,Bug-Off,ToolStcikInsect,8769
3,Bunny Day wand,Unlimited,11100,NaN,NaN,No,Crafting,ToolStickEgg,12578
4,cherry-blossom wand,Unlimited,2700,NaN,NaN,No,Crafting,ToolStickCherryblossom,7589
...,...,...,...,...,...,...,...,...,...
195,watering can,60,600,White,NaN,Yes,Crafting,ToolWatering_Remake_6_0,2379
196,watering can,60,600,Black,NaN,Yes,Crafting,ToolWatering_Remake_7_0,2379
197,wedding wand,Unlimited,3500,NaN,NaN,No,Wedding Season,ToolStickJune,12695
198,windflower wand,Unlimited,1580,NaN,NaN,No,Crafting,ToolStickAnemones,5084
199,worn axe,3,10,NaN,NaN,No,May Day Tour,ToolAxeFragile,12615

## 1.3 -- Removing empty data

In [21]:
df.isna().sum()

Name             0
Uses             0
Sell             0
Variation       44
Set            120
Customize        0
Source           0
Filename         0
Internal ID      0
dtype: int64

In [24]:
df = df[df['Set'].notna()]
df = df[df['Variation'].notna()]
df

,Name,Uses,Sell,Variation,Set,Customize,Source,Filename,Internal ID
5,colorful fishing rod,30,625,Yellow,Colorful Tools,Yes,Nook's Cranny,ToolFishingrodDuck_Remake_0_0,8472
6,colorful fishing rod,30,625,Orange,Colorful Tools,Yes,Nook's Cranny,ToolFishingrodDuck_Remake_1_0,8472
7,colorful fishing rod,30,625,Light blue,Colorful Tools,Yes,Nook's Cranny,ToolFishingrodDuck_Remake_2_0,8472
8,colorful fishing rod,30,625,Pink,Colorful Tools,Yes,Nook's Cranny,ToolFishingrodDuck_Remake_3_0,8472
9,colorful fishing rod,30,625,Green,Colorful Tools,Yes,Nook's Cranny,ToolFishingrodDuck_Remake_4_0,8472
...,...,...,...,...,...,...,...,...,...
140,outdoorsy watering can,60,625,Red,Outdoor Tools,Yes,Nook's Cranny,ToolWateringOutdoor_Remake_3_0,8536
141,outdoorsy watering can,60,625,Beige,Outdoor Tools,Yes,Nook's Cranny,ToolWateringOutdoor_Remake_4_0,8536
142,outdoorsy watering can,60,625,Pink,Outdoor Tools,Yes,Nook's Cranny,ToolWateringOutdoor_Remake_5_0,8536
143,outdoorsy watering can,60,625,Yellow,Outdoor Tools,Yes,Nook's Cranny,ToolWateringOutdoor_Remake_6_0,8536
144,outdoorsy watering can,60,625,Black,Outdoor Tools,Yes,Nook's Cranny,ToolWateringOutdoor_Remake_7_0,8536

## 1.4 -- Formatting data

In [25]:
df.dtypes

Name             str
Uses             str
Sell           int64
Variation        str
Set              str
Customize        str
Source           str
Filename         str
Internal ID    int64
dtype: object

In [28]:
df['Customize'] = df['Customize'].astype(bool)
df.dtypes

Name             str
Uses             str
Sell           int64
Variation        str
Set              str
Customize       bool
Source           str
Filename         str
Internal ID    int64
dtype: object

In [29]:
df.head()

,Name,Uses,Sell,Variation,Set,Customize,Source,Filename,Internal ID
5,colorful fishing rod,30,625,Yellow,Colorful Tools,True,Nook's Cranny,ToolFishingrodDuck_Remake_0_0,8472
6,colorful fishing rod,30,625,Orange,Colorful Tools,True,Nook's Cranny,ToolFishingrodDuck_Remake_1_0,8472
7,colorful fishing rod,30,625,Light blue,Colorful Tools,True,Nook's Cranny,ToolFishingrodDuck_Remake_2_0,8472
8,colorful fishing rod,30,625,Pink,Colorful Tools,True,Nook's Cranny,ToolFishingrodDuck_Remake_3_0,8472
9,colorful fishing rod,30,625,Green,Colorful Tools,True,Nook's Cranny,ToolFishingrodDuck_Remake_4_0,8472

# TASK 2 : DATA ANALYSIS

## 2.1 -- Rows count

In [31]:
df.shape

(80, 9)