# TASK 1 : PREPARING

In [3]:
import numpy as np
import pandas as pd

## 1.1 -- Importing dataset

In [35]:
df = pd.read_csv("./data/housewares.csv")
df

,Name,Variation,Body Title,Pattern,Pattern Title,DIY,Body Customize,Pattern Customize,Kit Cost,Buy,...,Interact,Tag,Outdoor,Speaker Type,Lighting Type,Catalog,Filename,Variant ID,Internal ID,Unique Entry ID
0,acoustic guitar,Natural,Body,NaN,NaN,Yes,Yes,No,5.0,NFS,...,Yes,Musical Instrument,No,Does not play music,No lighting,Not for sale,FtrAcorsticguitar_Remake_0_0,0_0,383,EpywQXABBcv2dipsP
1,acoustic guitar,Cherry,Body,NaN,NaN,Yes,Yes,No,5.0,NFS,...,Yes,Musical Instrument,No,Does not play music,No lighting,Not for sale,FtrAcorsticguitar_Remake_1_0,1_0,383,K9she5Y4SuXA8MGBR
2,acoustic guitar,Brown,Body,NaN,NaN,Yes,Yes,No,5.0,NFS,...,Yes,Musical Instrument,No,Does not play music,No lighting,Not for sale,FtrAcorsticguitar_Remake_2_0,2_0,383,vLq9iphAvALBXazDr
3,acoustic guitar,Blue,Body,NaN,NaN,Yes,Yes,No,5.0,NFS,...,Yes,Musical Instrument,No,Does not play music,No lighting,Not for sale,FtrAcorsticguitar_Remake_3_0,3_0,383,nuqeFzNE5PneqGHaj
4,acoustic guitar,White,Body,NaN,NaN,Yes,Yes,No,5.0,NFS,...,Yes,Musical Instrument,No,Does not play music,No lighting,Not for sale,FtrAcorsticguitar_Remake_4_0,4_0,383,DotFsojrhCwrLZ3TF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3270,zen-style stone,White granite,Stone,NaN,NaN,Yes,Yes,No,6.0,NFS,...,No,Japanese Style,Yes,Does not play music,No lighting,Not for sale,FtrGravestoneJapan_Remake_0_0,0_0,7317,xDuaerhiJuiJnwNDS
3271,zen-style stone,Andesite,Stone,NaN,NaN,Yes,Yes,No,6.0,NFS,...,No,Japanese Style,Yes,Does not play music,No lighting,Not for sale,FtrGravestoneJapan_Remake_1_0,1_0,7317,YfpPverX5Q2iEwRF2
3272,zen-style stone,Black granite,Stone,NaN,NaN,Yes,Yes,No,6.0,NFS,...,No,Japanese Style,Yes,Does not play music,No lighting,Not for sale,FtrGravestoneJapan_Remake_2_0,2_0,7317,nrzjikKKpni7sAMir
3273,zen-style stone,Brown granite,Stone,NaN,NaN,Yes,Yes,No,6.0,NFS,...,No,Japanese Style,Yes,Does not play music,No lighting,Not for sale,FtrGravestoneJapan_Remake_3_0,3_0,7317,7qXRema8baxyunhvS
3274,zen-style stone,Mossy stone,Stone,NaN,NaN,Yes,Yes,No,6.0,NFS,...,No,Japanese Style,Yes,Does not play music,No lighting,Not for sale,FtrGravestoneJapan_Remake_4_0,4_0,7317,RswDXvSEibYz7Zajy

In [36]:
df.head(5)

,Name,Variation,Body Title,Pattern,Pattern Title,DIY,Body Customize,Pattern Customize,Kit Cost,Buy,...,Interact,Tag,Outdoor,Speaker Type,Lighting Type,Catalog,Filename,Variant ID,Internal ID,Unique Entry ID
0,acoustic guitar,Natural,Body,NaN,NaN,Yes,Yes,No,5.0,NFS,...,Yes,Musical Instrument,No,Does not play music,No lighting,Not for sale,FtrAcorsticguitar_Remake_0_0,0_0,383,EpywQXABBcv2dipsP
1,acoustic guitar,Cherry,Body,NaN,NaN,Yes,Yes,No,5.0,NFS,...,Yes,Musical Instrument,No,Does not play music,No lighting,Not for sale,FtrAcorsticguitar_Remake_1_0,1_0,383,K9she5Y4SuXA8MGBR
2,acoustic guitar,Brown,Body,NaN,NaN,Yes,Yes,No,5.0,NFS,...,Yes,Musical Instrument,No,Does not play music,No lighting,Not for sale,FtrAcorsticguitar_Remake_2_0,2_0,383,vLq9iphAvALBXazDr
3,acoustic guitar,Blue,Body,NaN,NaN,Yes,Yes,No,5.0,NFS,...,Yes,Musical Instrument,No,Does not play music,No lighting,Not for sale,FtrAcorsticguitar_Remake_3_0,3_0,383,nuqeFzNE5PneqGHaj
4,acoustic guitar,White,Body,NaN,NaN,Yes,Yes,No,5.0,NFS,...,Yes,Musical Instrument,No,Does not play music,No lighting,Not for sale,FtrAcorsticguitar_Remake_4_0,4_0,383,DotFsojrhCwrLZ3TF

## 1.2 -- Filtering input

In [38]:
df = df[['Name', 'Variation', 'Pattern', 'DIY', 'Pattern Customize', 'Kit Cost', 'Sell', 'Source', 'Filename', 'Internal ID']]
df

,Name,Variation,Pattern,DIY,Pattern Customize,Kit Cost,Sell,Source,Filename,Internal ID
0,acoustic guitar,Natural,NaN,Yes,No,5.0,3210,Crafting,FtrAcorsticguitar_Remake_0_0,383
1,acoustic guitar,Cherry,NaN,Yes,No,5.0,3210,Crafting,FtrAcorsticguitar_Remake_1_0,383
2,acoustic guitar,Brown,NaN,Yes,No,5.0,3210,Crafting,FtrAcorsticguitar_Remake_2_0,383
3,acoustic guitar,Blue,NaN,Yes,No,5.0,3210,Crafting,FtrAcorsticguitar_Remake_3_0,383
4,acoustic guitar,White,NaN,Yes,No,5.0,3210,Crafting,FtrAcorsticguitar_Remake_4_0,383
...,...,...,...,...,...,...,...,...,...,...
3270,zen-style stone,White granite,NaN,Yes,No,6.0,4500,Crafting,FtrGravestoneJapan_Remake_0_0,7317
3271,zen-style stone,Andesite,NaN,Yes,No,6.0,4500,Crafting,FtrGravestoneJapan_Remake_1_0,7317
3272,zen-style stone,Black granite,NaN,Yes,No,6.0,4500,Crafting,FtrGravestoneJapan_Remake_2_0,7317
3273,zen-style stone,Brown granite,NaN,Yes,No,6.0,4500,Crafting,FtrGravestoneJapan_Remake_3_0,7317
3274,zen-style stone,Mossy stone,NaN,Yes,No,6.0,4500,Crafting,FtrGravestoneJapan_Remake_4_0,7317

## 1.3 -- Removing empty data

In [39]:
df.isna().sum()

Name                    0
Variation             202
Pattern              1881
DIY                     0
Pattern Customize       0
Kit Cost             1036
Sell                    0
Source                  0
Filename                0
Internal ID             0
dtype: int64

In [40]:
df = df[df['Variation'].notna()]
df = df[df['Pattern'].notna()]
df = df[df['Kit Cost'].notna()]
df

,Name,Variation,Pattern,DIY,Pattern Customize,Kit Cost,Sell,Source,Filename,Internal ID
74,baby chair,Red,Bear,No,Yes,1.0,300,Nook's Cranny,FtrBabychair_Remake_0_0,3305
75,baby chair,Red,Strawberry,No,Yes,1.0,300,Nook's Cranny,FtrBabychair_Remake_0_1,3305
76,baby chair,Red,Butterfly,No,Yes,1.0,300,Nook's Cranny,FtrBabychair_Remake_0_2,3305
77,baby chair,Red,Train,No,Yes,1.0,300,Nook's Cranny,FtrBabychair_Remake_0_3,3305
78,baby chair,Red,Paw print,No,Yes,1.0,300,Nook's Cranny,FtrBabychair_Remake_0_4,3305
...,...,...,...,...,...,...,...,...,...,...
3248,writing chair,Dark brown,Blue,No,Yes,1.0,425,Nook's Cranny,FtrStudyChair_Remake_2_1,3702
3249,writing chair,Dark brown,Pink,No,Yes,1.0,425,Nook's Cranny,FtrStudyChair_Remake_2_2,3702
3250,writing chair,White,Yellow,No,Yes,1.0,425,Nook's Cranny,FtrStudyChair_Remake_3_0,3702
3251,writing chair,White,Blue,No,Yes,1.0,425,Nook's Cranny,FtrStudyChair_Remake_3_1,3702
3252,writing chair,White,Pink,No,Yes,1.0,425,Nook's Cranny,FtrStudyChair_Remake_3_2,3702

## 1.4 -- Formatting data

In [41]:
df.dtypes

Name                     str
Variation                str
Pattern                  str
DIY                      str
Pattern Customize        str
Kit Cost             float64
Sell                   int64
Source                   str
Filename                 str
Internal ID            int64
dtype: object

In [42]:
df['Pattern Customize'] = df['Pattern Customize'].astype(bool)
df['DIY'] = df['DIY'].astype(bool)
df.dtypes

Name                     str
Variation                str
Pattern                  str
DIY                     bool
Pattern Customize       bool
Kit Cost             float64
Sell                   int64
Source                   str
Filename                 str
Internal ID            int64
dtype: object

In [43]:
df.head()

,Name,Variation,Pattern,DIY,Pattern Customize,Kit Cost,Sell,Source,Filename,Internal ID
74,baby chair,Red,Bear,True,True,1.0,300,Nook's Cranny,FtrBabychair_Remake_0_0,3305
75,baby chair,Red,Strawberry,True,True,1.0,300,Nook's Cranny,FtrBabychair_Remake_0_1,3305
76,baby chair,Red,Butterfly,True,True,1.0,300,Nook's Cranny,FtrBabychair_Remake_0_2,3305
77,baby chair,Red,Train,True,True,1.0,300,Nook's Cranny,FtrBabychair_Remake_0_3,3305
78,baby chair,Red,Paw print,True,True,1.0,300,Nook's Cranny,FtrBabychair_Remake_0_4,3305

# TASK 2 : DATA ANALYSIS

## 2.1 -- Rows count

In [44]:
df.shape

(1315, 10)